export const FORM_SUBMISSION = 'FORM_SUBMISSION'
export const GET_DATA = 'GET_DATA'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_START = 'AUTH_START'
